"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')k!u@9o=1n&1szwqjc#igm!$qa^3cyf%7fh24ml(6$(c0&-^3!'


'''DEBUG is a boolean that turns the debug mode of the project on and off. If it is set to True, Django
 will display detailed error pages when an uncaught exception is thrown by your application. When you 
 move to a production environment, remember that you have to set it to False. Never deploy a site into 
 production with DEBUG turned on because you will expose sensitive project-related data.'''
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


'''ALLOWED_HOSTS is not applied while debug mode is on, or when the tests are run. Once you move your site to 
production and set DEBUG to False, you will have to add your domain/host to this setting in order to allow it 
to serve your Django site.'''
ALLOWED_HOSTS = []


# Application definition
'''INSTALLED_APPS is a setting you will have to edit for all projects. This setting tells Django which 
applications are active for this site'''
INSTALLED_APPS = [
    'django.contrib.admin',                    #an administration site
    'django.contrib.auth',                      #An authentication framework
    'django.contrib.contenttypes',              #A framework for handling content types
    'django.contrib.sessions',                  #A Session Framework
    'django.contrib.messages',                  #A messaging framework
    'django.contrib.staticfiles',               #A framework for nanaging static files
    'blog.apps.BlogConfig',                    #activating blog application for our project
    'taggit', 
    'django.contrib.sitemaps',  
    'django.contrib.sites',                              
]

"""
MIDDLEWARE is a list that contains middleware to be executed."""

SITE_ID=1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

'''indicates the Python module where the root URL patterns of your application are defined.'''
ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


'''DATABASES is a dictionary that contains the settings for all the databases to be used in the project.
 There must always be a default database. The default configuration uses an SQLite3 database.'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


"""LANGUAGE_CODE defines the default language code for this Django site."""
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True


"""USE_TZ tells Django to activate/deactivate timezone support. Django comes with support for 
timezone-aware datetime. This setting is set to True when you create a new project using the startproject 
management command."""
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'


EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='sandipneupane65@gmail.com'
EMAIL_HOST_PASSWORD='sandip_nup123'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False
